### ISSUE TITLE
Prediction with tiling fails after successful training 

### ISSUE THREAD

**Issue by jkim08** [mpicbg-csbd/stardist#15] opened 2019-09-11 20:19 UTC
The training for the model seems to have worked but when I load an image stack for prediction (+tiling) the error message printed below is prompted. The demo model works fine with the test image stack, so it may have something to do with the model. 
Any help in explaining or circumventing this problem would be highly appreciated.

> Traceback (most recent call last):
>   File "_prediction_file_name_", line 65, in <module>
>     labels, details = model.predict_instances(img, n_tiles=(1,4,4))
>   File "/home/isim/anaconda3/lib/python3.7/site-packages/stardist/models/base.py", line 364, in predict_instances
>     prob, dist = self.predict(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles, show_tile_progress=show_tile_progress, **predict_kwargs)
>   File "/home/isim/anaconda3/lib/python3.7/site-packages/stardist/models/base.py", line 279, in predict
>     axes_net_tile_overlaps = self._axes_tile_overlap(axes_net)
>   File "/home/isim/anaconda3/lib/python3.7/site-packages/stardist/models/base.py", line 448, in _axes_tile_overlap
>     self._tile_overlap = self._compute_receptive_field()
>   File "/home/isim/anaconda3/lib/python3.7/site-packages/stardist/models/base.py", line 440, in _compute_receptive_field
>     return [(m-np.min(i), np.max(i)-m) for (m,i) in zip(mid,ind)]
>   File "/home/isim/anaconda3/lib/python3.7/site-packages/stardist/models/base.py", line 440, in <listcomp>
>     return [(m-np.min(i), np.max(i)-m) for (m,i) in zip(mid,ind)]
>   File "/home/isim/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2618, in amin
>     initial=initial)
>   File "/home/isim/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
>     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
> ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by maweigert** [comment] 2019-09-11 20:31
Hi, 

What `Config3D` is used and what is the shape of `img`?

**Comment by jkim08** [comment] 2019-09-11 20:37
Thank you for your reply!

conf = Config3D (
    rays             = rays,
    grid             = grid,
    anisotropy       = anisotropy,
    use_gpu          = use_gpu,
    n_channel_in     = n_channel,
    # adjust for your data below (make patch size as large as possible)
    train_patch_size = (48,192,96),
    train_batch_size = 2,
)

The shape of img is 60x1024x1024 for zyx.

**Comment by maweigert** [comment] 2019-09-11 20:59
Strange, I cannot reproduce this...

Could you attach the zipped model folder (that includes the config.json, the weights etc)?

**Comment by wangyuhan01** [comment] 2019-10-11 20:41
Not sure if this is relevant, but when I have empty values in my training data (pixels where there is no image foreground/background), I got the exact same error message in my predictions with the trained model.

**Comment by maweigert** [comment] 2019-11-15 15:48
Closing for now as it seems to be related to #25 (thanks @wangyuhan01!)

**Closed by maweigert** 2019-11-15 15:48 UTC
