### ISSUE TITLE
Kernel dies during run of 3D example

### ISSUE THREAD

**Issue by max-brambach** [mpicbg-csbd/stardist#14] opened 2019-08-27 12:49 UTC
When running the 3D example, the python kernel of the jupyter notebook dies. No further error is raised.
This happens when executing the following line of the file 3_prediction:
`labels, details = model.predict_instances(img)`
and the following line of file 2_training:
`model.optimize_thresholds(X_val, Y_val)`
In both cases, the supplied 3D_demo model was used.
The 2D example runs without error.

Could it be that the model file is corrupt?

**Comment by max-brambach** [comment] 2019-08-30 13:07
The console in which jupyter is running gives the following message:
`2019-08-30 14:54:25.846088: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2`

I've tried the example on a Linux machine with CUDA and it runs without error.

**Comment by wangyuhan01** [comment] 2019-09-02 02:57
Encountered the same problem on a windows machine. Kernel dies when executing `labels, details = model.predict_instances(img)` with example data and 3D_demo model.

**Comment by uschmidt83** [comment] 2019-09-02 08:01
> The console in which jupyter is running gives the following message:
> `2019-08-30 14:54:25.846088: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2`

This is a common warning raised by TensorFlow and not the problem.

> I've tried the example on a Linux machine with CUDA and it runs without error.

Your problem only happens on Windows?

**Comment by uschmidt83** [comment] 2019-09-02 08:07
I think the problem is caused by the compiled C++ extension, but I need to see an error message.

Can you please execute the `3_prediction.ipynb` notebook on the command line as follows and then copy and paste the output (including the error message) into a text file?

`jupyter nbconvert --execute --to notebook --inplace --ExecutePreprocessor.timeout=3600 3_prediction.ipynb`

**Comment by wangyuhan01** [comment] 2019-09-02 11:21
Hi Uwe,

Attached is the error message I got. Seems to have something to do with the GPU requirements?

Thanks,
Yuhan

[error.txt](https://github.com/mpicbg-csbd/stardist/files/3565797/error.txt)

**Comment by uschmidt83** [comment] 2019-09-02 12:07
Thanks, Yuhan!

Unfortunately, it doesn't help me to track down the problem. Could you download the notebook as a python script from [here](https://nbviewer.jupyter.org/format/script/github/mpicbg-csbd/stardist/blob/master/examples/3D/3_prediction.ipynb), name it `3_prediction.py`, and then run it from the command line via `python 3_prediction.py`. Maybe that will produce a more useful error message...

**Comment by max-brambach** [comment] 2019-09-02 14:22
Hi Uwe,
I've also run the notebook and scrip as you instructed and here is what the console returned.
[console_output_stardist_notebook.txt](https://github.com/mpicbg-csbd/stardist/files/3566354/console_output_stardist_notebook.txt)
[console_output_stardist_script.txt](https://github.com/mpicbg-csbd/stardist/files/3566355/console_output_stardist_script.txt)
For the script to run I had to comment out lines 11 and 12.

**Comment by uschmidt83** [comment] 2019-09-02 15:41
> For the script to run I had to comment out lines 11 and 12.
> However, this does not produce an error message.

I don't understand. The script runs through without an error? But the notebook does not?

**Comment by wangyuhan01** [comment] 2019-09-02 16:02
Hi Uwe,

Thanks, also have to comment out lines 11 and 12. Seems to be an known issue for converting notebook to .py script when using %matplotlib inline. Attached is what I got from the run, no error,  but also didn't seem I should expect any output? 
[console_py.txt](https://github.com/mpicbg-csbd/stardist/files/3566644/console_py.txt)

**Comment by max-brambach** [comment] 2019-09-03 07:24
In both cases the execution stops while calling `model.predict_instances(img)` and exits without raising an error.

**Comment by uschmidt83** [comment] 2019-09-03 08:46
Hmm, that makes it hard for me to debug.

What version of Windows and C++ compiler (Visual Studio) are you using?

**Comment by michielkleinnijenhuis** [comment] 2019-09-20 09:39
Hello Uwe,

I seem to be experiencing the same issue on Windows 10 (VS 2019 v16.1.1). Do you have any updates?

Thank you, Michiel

**Comment by uschmidt83** [comment] 2019-09-22 15:14
Hi Michiel,

I can [re-produce the issue](https://ci.appveyor.com/project/UweSchmidt/stardist/builds/27579928) in our automated tests, but don't yet know what the cause is.
I will try to fix this as soon as possible.

**Comment by maweigert** [comment] 2019-09-24 21:43
Hi,
 
The described bug on Windows (dead kernel after `model.predict_instances`)  should hopefully fixed in the latest release of stardist (`0.3.3`). 

@max-brambach @michielkleinnijenhuis  Could you update and see if it now runs without crashing? Thanks!

**Comment by michielkleinnijenhuis** [comment] 2019-09-26 09:12
Hi Martin,

Thanks for the update. I've just tried and got the 3D example running by updating to 0.3.4 from Github. Please note that you seem to have left a hardcoded path in the pypi version ([stardist_3D_bugreport_reinstall_from_pip.txt](https://github.com/mpicbg-csbd/stardist/files/3656970/stardist_3D_bugreport_reinstall_from_pip.txt)).

Really excited to start exploring your method!

best wishes, Michiel

**Comment by maweigert** [comment] 2019-09-26 12:40
Hi @michielkleinnijenhuis,

Good catch! Should be fixed in the latest pypi version.
Thanks!

**Closed** 2019-09-27 10:09 UTC
